# Generated by Django 5.1.4 on 2025-01-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model3',
            new_name='Autor',
        ),
        migrations.RenameModel(
            old_name='Model2',
            new_name='Libro',
        ),
        migrations.RenameModel(
            old_name='Model1',
            new_name='Persona',
        ),
    ]
